### ISSUE TITLE
Данные из базы выводятся без экранирования.

### ISSUE THREAD

**Issue by vas-and-tor** [smi2/clickhouse-frontend#11]
Вместо тысячи слов:
`select '<script>alert("Привет! Я XSS.");</script>';`

**Comment by atomlipetsk** [comment]
Спасибо! Исправил в 1.1.3

**Comment by vas-and-tor** [comment]
Не совсем то, что хотелось.
Хотелось экранирования, а не удаления.

**Comment by isublimity** [comment]
Мы обновляем сейчас весь GUI на других компонентах => будет другой рендер )
