### ISSUE TITLE
redirect to https

### ISSUE THREAD

**Issue by Negashev** [smi2/clickhouse-frontend#14]
пытаюсь подключиться по https к clickhouse в консоли выдает ошибку:

`
XMLHttpRequest cannot load http://clickhouse.negash.ru/?query=show%20databases%20%20FoRmAt%20JSON&us…l&password=pass&add_http_cors_header=1. Redirect from 'http://clickhouse.negash.ru/?query=show%20databases%20%20FoRmAt%20JSON&us…l&password=pass&add_http_cors_header=1' to 'https://clickhouse.negash.ru/?query=show%20databases%20%20FoRmAt%20JSON&u…l&password=pass&add_http_cors_header=1' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://ui.negash.ru' is therefore not allowed access.
`

**Comment by isublimity** [comment]
А если убрать все редиректы ? 
Попробовать вбить IP сразу CH или clickhouse.negash.ru  ?

**Comment by Negashev** [comment]
@isublimity При каждом запросе мы передаем логин и пароль в открытом виде, и это не безопасно, по этому имеет смысл подключить https

**Comment by isublimity** [comment]
см https://github.com/yandex/ClickHouse/pull/83

Предполагается что используется IPtables + и работа идет из внутренней сети под VPN
