### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by sichkarev** [smi2/clickhouse-frontend#15]
Добрый день!

При подключении к серверу КликХаус пишет "Ошибка доступа".
![image](https://cloud.githubusercontent.com/assets/16035271/20050427/1e722586-a4eb-11e6-8aaf-133bfdc13fe3.png)

Во время запуска возникают ошибки:
![image](https://cloud.githubusercontent.com/assets/16035271/20050312/668eed32-a4ea-11e6-8b6c-b90f0dabc51b.png)

ОС: Windows 10 
Node: v5.9.0
Bower: 1.7.9

P.S. Пользуясь случаем хочу поблагодарить вашу команду за активность в части разработки коннектора для PHP.

**Comment by atomlipetsk** [comment]
Попробуйте указать хост с портом 
192.168.22.71:8123

**Comment by sichkarev** [comment]
Так сработало, спасибо.
Сделайте пожалуйста чтобы без явного указания использовался порт по умолчанию.

**Comment by atomlipetsk** [comment]
Добавил дефолтный порт
