### ISSUE TITLE
Пожелания (для roadmap)

### ISSUE THREAD

**Issue by sichkarev** [smi2/clickhouse-frontend#17]
Если позволите, выскажу несколько предложений:
1. Сделать по-умолчанию сохранение набранных пользователем запросов, чтобы при повторном входе предыдущее состояние сессии восстанавливалось, сейчас если не сохранил принудительно, то вся работа аналитика сбрасывается.
2. Реализовать возможность задания имени вкладки с запросом по двойному клику на имени вкладки. Очень удобно с учетом реализации первого пункта.
3. Было бы очень круто выводить результат запроса в виде диаграммы. Хотя бы несколько основных видов. 
4. Экспорт результата с указанием формата, в каком виде данные будут отданы.
5. В тексте запроса, при выборе функции из выпадающего списка, нужно подставлять не только имя функции, но и выводить скобки с указанием списка свойств функции, и фильтровать варианты выпадающего списка по допустимом типу. Т.е. не просто "substringUTF8", а substringUTF8(s, offset, length) с автоматической установкой курсора в s и открытием выпадающего списка. При выборе переходим к сл. атрибуту...

Спасибо за работу!

**Comment by feriat** [comment]
Невероятно плюсую 1 и 4 :+1: 

Кроме того дополню своим:
6. Поддержать возможность устанавливать настройки для севера. SET не работает (видимо потому что запрос посылается в режиме одного запроса), а HTTP параметр указать негде.
7. При первом открытии открывать database default, а не первую в списке

**Comment by isublimity** [comment]
Спасибо за добавление в roadmap ) 

1) Добавили - "Лог запросов" - http://take.ms/MLhMo

2) Да подумаем 

3) В планах, прикрутить несколько рендеров - это оно  

```
Изменить Grid, выбрать из [ui-grid.info | ag-grid | paramquery.com | js-grid.com], сортировка на клиенте
Возможно выбрать pivotJs таблицы, c поддержкой D3/C3
```

4) Тут не понял, уточните, можно сделать так:

```
select * from xx.xxx limit 1  FORMAT TabSeparated
```

5) .... выводить скобки с указанием списка свойств функции... - это боюсь уже за приделами https://ace.c9.io - редактора, но самому не хватает этих фичь, попробую может получится 

6) Да будет "Поддержать возможность устанавливать настройки" 

7) Тут думаю не угодишь всем, у нас на оборот база ads - она первая ) 

Думаю можно прикрутить "запоминатель" последней выбранной базы

**Comment by sichkarev** [comment]
По первому пункту я имел ввиду немного большее чем просто лог запросов. Допустим я подключился к КХ, создал 20 вкладок с запросами, которые используются ежедневно / периодически.
![image](https://cloud.githubusercontent.com/assets/16035271/20085903/02eb657c-a58e-11e6-8fe6-0f566847a51d.png)
Сейчас, если я закрою страницу, то при повторном открытии нужно будет заново формировать этот список - это крайне неудобно. Я предлагаю сделать так, чтобы список вкладок, их содержимое загружалось автоматически при подключении.

По п.4.
Я говорю о полноценном экспорте результатов запроса в файл, т.к. порой результаты нужны для анализа не в браузере, а в стороннем ПО. Допустим из последнего, в Хроме результаты даже в FORMAT TabSeparated скопировать через буфер обмена в Excel получается только через копипаст в Notepad++ - сначала в него, а потом в Excel, иначе он не понимает :)
Вот даже по быстрому накидал эскиз того, что я предлагаю сделать.
![image](https://cloud.githubusercontent.com/assets/16035271/20086636/9ac737f4-a593-11e6-94e8-ab6411b92bc3.png)

**Comment by atomlipetsk** [comment]
> Сделать по-умолчанию сохранение набранных пользователем запросов, чтобы при повторном входе предыдущее состояние сессии восстанавливалось, сейчас если не сохранил принудительно, то вся работа аналитика сбрасывается.

Реализовано в сборке https://github.com/smi2/clickhouse-frontend/releases/tag/1.3.6
![](http://pix.toile-libre.org/upload/original/1478597696.jpg)

**Comment by atomlipetsk** [comment]
> Реализовать возможность задания имени вкладки с запросом по двойному клику на имени вкладки. Очень удобно с учетом реализации первого пункта.

Сделал в киде кнопки. Двойной клик оказался неудобен.
![](http://pix.toile-libre.org/upload/original/1478685291.jpg)

**Comment by atomlipetsk** [comment]
> Экспорт результата с указанием формата, в каком виде данные будут отданы.

Доступны CSV и табулированный текст. Сборка 1.4.8
![](http://pix.toile-libre.org/upload/original/1478781726.jpg)

**Comment by isublimity** [comment]
смотрите https://tabix.io/doc/
