### ISSUE TITLE
FORMAT Vertical

### ISSUE THREAD

**Issue by sichkarev** [smi2/clickhouse-frontend#18]
Можно-ли как-то представить широкую таблицу вертикально?
Когда пишу FORMAT Vertical - возвращает ошибку:
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 1031 (line 15, col 24): FORMAT JSON 
, expected UNION, e.what() = DB::Exception

**Comment by isublimity** [comment]
https://github.com/smi2/clickhouse-frontend/commit/936627389cf1c2f893d85619044247872de5b171
