### ISSUE TITLE
Пролистывание затруднительно

### ISSUE THREAD

**Issue by sichkarev** [smi2/clickhouse-frontend#19]
Когда вкладок много пролистывание затруднительно. При нажатии на стрелке открывается диалог настроек. Пролистывание возможно только при нажатии на часть следующей вкладки.
![image](https://cloud.githubusercontent.com/assets/16035271/20086855/554e32de-a595-11e6-92c8-a0e54f4d5e6a.png)

**Comment by atomlipetsk** [comment]
fixed 
![](http://pix.toile-libre.org/upload/original/1478599237.jpg)
