### ISSUE TITLE
Single query fails if it ends with a single semicolon

### ISSUE THREAD

**Issue by hatarist** [smi2/clickhouse-frontend#23]
Running a single query:
```SELECT 1;```

Fails with a traceback:
```
Code: 62, e.displayText() = DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 12: FORMAT JSON 
, e.what() = DB::Exception
```

It sends that as `SELECT 1; FORMAT JSON` to the server.
`SELECT 1;;` works, but didn't seem intuitive for me. Sorry!

Thanks in advance!

**Comment by isublimity** [comment]
https://github.com/smi2/clickhouse-frontend/commit/a92ed41bd83e57f8cea4f4d8cdf4dba148592a03

https://github.com/smi2/clickhouse-frontend/commit/11826099645eadd86b410458354b9b619d23e27d
