### ISSUE TITLE
Отображение пустой базы

### ISSUE THREAD

**Issue by DrStep** [smi2/clickhouse-frontend#25]
Привет!
Спасибо за продукт. Собрали и развернули у себя проект. Проблема следующая: при создании новой (пустой) базы в интерфейсе она не отображается, мне кажется, это некорректное поведение (и не интуитивное, долго просидел, пытаясь понять, что не так :) ), думаю, стоит пофиксить

**Comment by DrStep** [comment]
И еще 2 момента по созданию: было бы здорово, если бы панель с базами/таблицами обновлялась после создания новой базы/таблицы
![image](https://cloud.githubusercontent.com/assets/4700511/21056264/ef5d4f40-be45-11e6-9c4c-8a5991bbc79a.png)
а то каждый раз обновлять страницу не очень удобно

**Comment by isublimity** [comment]
смотрите https://tabix.io/doc/
