### ISSUE TITLE
Wierd characters in README.md

### ISSUE THREAD

**Issue by mannol** [smi2/clickhouse-frontend#27]
There are some wierd characters rendered in README.md; it's impossible to read and making README usless!

Anyways I've outlined the parts with the wierd characters: 

![wierd_characters](https://cloud.githubusercontent.com/assets/13100554/21106365/1c2c164c-c08e-11e6-9eb9-dfa363177057.png)

I hope it's a firefox bug at my end...

**Comment by isublimity** [comment]
А что с русским языком не так?

**Comment by mannol** [comment]
I see them again in your comment; it appears this repo is the only one affected by this wierd bug...

**Comment by isublimity** [comment]
Use google translate , for Russian language-> Eng
