### ISSUE TITLE
Nginx config

### ISSUE THREAD

**Issue by samriang** [smi2/clickhouse-frontend#34]
Hello, good people.

Can anybody share working nginx config for this panel?

I am using very simple config with single root location and there is always error in browser console:

`No 'Access-Control-Allow-Origin' header is present on the requested resource`

Setting 
`        add_header 'Access-Control-Allow-Origin' '*';`
in nginx.conf doesn't solve problem.

Thanks!

**Comment by samriang** [comment]
Was my bad. Works without any special tuning. Issue could be closed.

**Comment by freezhan** [comment]
When when I want to  login http://ui.tabix.io/ appear the same problem, how do you solve it
