### ISSUE TITLE
FR: Compare results mode

### ISSUE THREAD

**Issue by f1yegor** [smi2/clickhouse-frontend#35]
Хотелось бы такую фичу - чтобы было удобно сравнивать результаты двух запросов(в частности когда занимаешься оптимизацией запросов и подгоняешь под одинаковые ответы). т.е. сейчас я это делаю в двух табах консоли(clickhouse-cli). Важно чтобы результаты переключались мгновенно(без эффекта слайда как в chgui), и были расположены в одном месте(т.е. независимо от длины запроса позиционировались одинаково). Чтобы при переключении табов(хоткей есть на это дело?) в chgui я быстро сравнивал цифры.
Можно рассмотреть вариант двух запросов и результатов на одной странице.

**Comment by isublimity** [comment]
Будет возможность поставить рядом результат двух таблиц 
https://monosnap.com/file/h3MwDt90PRr5aruaCnv6OPI0h9s2BO

**Comment by hagen1778** [comment]
Возможно, это можно решить добавлением кнопки Copy, которая бы копировала рез-т запроса. Таким образом, Вы могли бы быстро скопировать оба рез-та и сравнить в подходящем для этого инструменте. Например, в IDE
