### ISSUE TITLE
Язык по умолчанию и выбор языка.

### ISSUE THREAD

**Issue by Hamper** [smi2/clickhouse-frontend#36]
На сколько я понял, по умолчанию устанавливается русский язык, и на английский переключается только если в браузере установлен английский, что не удобно для пользователей из других стран, которые, скорее всего, понимают английский, но совсем не понимают русский, а возможности переключения языка в интерфейсе тоже нет. Может стоит поменять язык по умолчанию на анлийский и переключать на русский только если он установлен в браузере или хотя бы сделать возможно переключать язык через интерфейс?

**Comment by isublimity** [comment]
Добавив в следующем релизе - выбор языка

**Comment by isublimity** [comment]
in dev & master
