### ISSUE TITLE
Нужна возможность поделиться ссылкой на запрос

### ISSUE THREAD

**Issue by yuri-karpovich** [smi2/clickhouse-frontend#38]
Есть ли возможность делиться ссылкой, при переходе на которую будет выполнятсья запрос, переданный в URL?

**Comment by isublimity** [comment]
Это запланировано на Q2, сейчас планируется, до конца Q1 - выложить большое обновление GUI, после уже реализовывать серверную часть. 

Т/к чтобы расшарить запрос нужно его где-то сохранить + сохранить логин/пароль в базу. 

А пробросить просто через GET параметр URL - это не реально для длинных запросов.

**Comment by yuri-karpovich** [comment]
@isublimity Спасибо за отчвет! С нетерпением жду фичу. 
И спасибо за тул!

**Comment by yuri-karpovich** [comment]
Наверное пусть повисит открытой :)

**Comment by isublimity** [comment]
смотрите https://tabix.io/doc/ и roadmap
