### ISSUE TITLE
Не собирается production на node 6.10 x64

### ISSUE THREAD

**Issue by cherts** [smi2/clickhouse-frontend#39]
D:\Temp\clickhouse-frontend\src\app\index.config.js
  122:26  error  Unexpected trailing comma  comma-dangle

D:\Temp\clickhouse-frontend\src\app\sql\ace-mode-clickhouse.js
   17:7   error  "identifier" is defined but never used  no-unused-vars
  112:22  error  Unexpected trailing comma               comma-dangle
  190:8   error  "startRow" is defined but never used    no-unused-vars
  190:21  error  "startCol" is defined but never used    no-unused-vars
  241:8   error  "range1" is already defined             no-redeclare
  242:8   error  "text" is already defined               no-redeclare

D:\Temp\clickhouse-frontend\src\app\sql\sql.js
  132:10  error  Missing semicolon
                       semi
  157:21  error  You should use the angular.isObject method
                       angular/typecheck-object
  215:22  error  You should use the angular.isObject method
                       angular/typecheck-object
  216:21  error  You should use the angular.isString method
                       angular/typecheck-string
  321:41  error  Instead of !angular.isDefined, you can use the out-of-box angul
ar.isUndefined method  angular/definedundefined
  773:10  error  Unnecessary semicolon
                       no-extra-semi

? 13 problems (13 errors, 0 warnings)

[11:10:26] all files 68.17 kB
[11:10:26] Finished 'scripts' after 14 s
[11:10:26] Starting 'inject'...
[11:10:27] gulp-inject 1 files into index.html.
[11:10:28] gulp-inject 15 files into index.html.
[11:10:28] Finished 'inject' after 1.24 s
[11:10:28] Finished 'partials' after 7.98 s
[11:10:28] Starting 'html'...
[11:10:29] Finished 'fonts' after 8.91 s
[11:10:29] gulp-inject 2 files into index.html.
[11:11:10] docs\ styles\app-dbf3098b54.css 10.88 kB
[11:11:10] docs\ styles\vendor-1fc36a56a3.css 531.6 kB
[11:11:10] docs\ scripts\app-eda50f7ef3.js 49.16 kB
[11:11:10] docs\ scripts\vendor-736ac29651.js 1.94 MB
[11:11:10] docs\ index.html 864 B
[11:11:10] docs\ all files 2.53 MB
[11:11:10] Finished 'html' after 42 s
[11:11:10] Starting 'build'...
[11:11:10] Finished 'build' after 11 ?s

**Comment by isublimity** [comment]
Можно не собирать проект, он лежит собранный в папке doc 
https://github.com/smi2/clickhouse-frontend/tree/master/docs
или использовать хостенную версию http://guiclickhouse.smi2.ru/

**Comment by isublimity** [comment]
Ветка master сейчас рассматривается как deprecated, в ближайшее время будет новая версия

**Comment by cherts** [comment]
Какая-то странная у Вас политика разработки, master вдруг стала как deprecated, хотя у всех она обычно developer.  Проект не собирается из исходников, ну да бог с ним, используйте нашу версию на http://guiclickhouse.smi2.ru - я не хочу использовать вашу версию на вашем сайте, к тому же он помечается DrWeb как не рекомендуемый к посещению как и сам сайт smi2,.ru.

**Comment by isublimity** [comment]
Если откатиться на это коммит `c9f00eb82164eff5a23fcd231a31583c22dd0c75` то должен собраться на ура, по ошибки добавили в эту репу коммиты
Откачу их позже.

**Comment by isublimity** [comment]
смотрите https://tabix.io/doc/
