### ISSUE TITLE
Проблема запуска docker контейнера

### ISSUE THREAD

**Issue by stder** [smi2/clickhouse-frontend#40]
Пытаюсь по мануалу запустить контейнер с приложением.
Контейнер запускается, но при открытии приложения через Web интерфейс вижу в консоли
http://joxi.ru/bmozyJqSxjXYOr

**Comment by imsha** [comment]
Присоединяюсь.
Развернул без doker, ошибка такая же 

Uncaught Error: [$injector:modulerr] Failed to instantiate module SMI2 due to: ...

При сборке ошибки http://take.ms/cXt3r

**Comment by isublimity** [comment]
https://github.com/smi2/clickhouse-frontend/issues/39

Забыл откатить коммиты , если получится сегодня сделаю ((
