### ISSUE TITLE
Не работает запрос CREATE TABLE

### ISSUE THREAD

**Issue by umaxfun** [smi2/clickhouse-frontend#6]
Привет!

Спасибо за прекрасный продукт :) 

Как вижу, не работает запрос CREATE TABLE:
<img width="660" alt="screen shot 2016-09-21 at 09 06 40" src="https://cloud.githubusercontent.com/assets/521752/18699538/beb01c5a-7fda-11e6-9c31-25297ecf2d49.png">

Но, в том же подключении, работает селект из этой таблицы (после создания с помощью строго того же запроса, но через другой клиент).
<img width="705" alt="screen shot 2016-09-21 at 09 08 01" src="https://cloud.githubusercontent.com/assets/521752/18699610/1afb939a-7fdb-11e6-9435-16a1cefb02be.png">

**Comment by umaxfun** [comment]
Запрос: 

``` sql
CREATE TABLE newTable
    (
        _id String,
        edate Date,
        dt DateTime,
        actionName String,
        actionValue String,
        appId String,
        source String,
        sessionId String,
        userId String
    ) ENGINE=MergeTree (edate, (dt, userId), 8192)
```

**Comment by isublimity** [comment]
Добавили возможность отправить запрос без дополнения FORMAT JSON 

https://monosnap.com/file/JGFGjY0UsAT5zMUsmYDbwZUTyQK01G

http://guiclickhouse.smi2.ru/sql
